#!/usr/bin/env bash
# Script to configure UFW for port forwarding from port 8080 to port 80

# Enable kernel IP forwarding
sudo sed -i '/^#net.ipv4.ip_forward=1/s/^#//g' /etc/sysctl.conf
sudo sysctl -p

# Edit UFW before.rules file to add NAT rule
sudo bash -c 'cat <<EOT >> /etc/ufw/before.rules
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
EOT'

# Allow port 8080 in UFW
sudo ufw allow 8080/tcp

# Reload UFW to apply changes
sudo ufw disable
sudo ufw enable

