#!/usr/bin/env bash
# This script installs and configures Nginx to serve "Hello Holberton" on port 80

apt-get update -y && apt-get install -y nginx
service nginx stop || true
echo "Hello Holberton" > /var/www/html/index.html
service nginx start

