#!/usr/bin/env bash
# Script that installs nginx and configures it to redirect /redirect_me and set up a custom 404 page.

# Install Nginx
sudo apt update -y
sudo apt install nginx -y

# Set up web root and custom pages
mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Store configuration content
new_config=\ 
"server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
"
echo "$new_config" | sudo tee /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo nginx -s reload

